variables:
   GIT_SUBMODULE_STRATEGY: recursive
   ORD_SOUMET_W: "10"
   ORD_SOUMET_C: "30"
   ORD_SOUMET_M: "16G"
   ORD_SOUMET_TMPFS: "256M"

.env:
   build:
      - echo "No specific environment"
   variables:
      ALLOW_FAILURE_ARCHS: "ubuntu-22.04-amd64_gnu-11.4.0|rhel-8-amd64_gnu-14.1.0|rhel-8-amd64_gnu-9.3.0|rhel-9-amd64_gnu-11.5.0"

include:
   - project: 'RPN-SI/ci-admin'
     ref: dev
     file: '/ci/.gitlab-ci-config.yml'

build:rhel-8-amd64_gnu-14.2.0:
   variables:
      ECCI_ARCH : rhel-8-amd64_gnu-14.2.0
   stage: build
   tags:
      - concurrent
   script:
      - unset SSMUSE_LD_PREPEND
      - . r.load.dot ${ECCI_ENV}/exp/rhel-8-amd64-64@gnu-14.2.0
      - !reference [.env, build]
      - mkdir -pv ${PIPELINE_SUBDIR}/build_${ECCI_ARCH}
      - SRC_DIR=$(pwd)
      - cd ${PIPELINE_SUBDIR}/build_${ECCI_ARCH}
      - cmake -DCMAKE_VERBOSE_MAKE_FILE=ON ${SRC_DIR}
      - time make -j $NCPUS
   rules:
      - if: $ECCI_ARCH =~ $ALLOW_FAILURE
        allow_failure: true
      - when: always

test:rhel-8-amd64_gnu-14.2.0:
   variables:
      ORD_SOUMET_MPI : mpi
      ORD_SOUMET_M : 1G
   script:
      - set +e
      - unset SSMUSE_LD_PREPEND
      - . r.load.dot ${ECCI_ENV}/exp/rhel-8-amd64-64@gnu-14.2.0
      - !reference [.env, build]
      - set -e
      - cd ${PIPELINE_SUBDIR}/build_${ECCI_ARCH}
      - echo F_FLAGS=${F_FLAGS}
      - env | grep LD | sort
      - make check || mpirun -n 1 ldd test/atomic

#deploy:staging:
#   stage: deploy
#   only:
#      - master
#      - tags
#      - dev
#      - schedules
#   script:
#      - ~/ci-admin-bundle/bin/ci-stage-ssm.sh libs ${CI_PROJECT_NAME} "${CI_COMMIT_TAG}" "${ECCI_PROCESS}"
