variables:
   GIT_SUBMODULE_STRATEGY: recursive
   ORD_SOUMET_W: "10"
   ORD_SOUMET_C: "1"
   ORD_SOUMET_M: "4G"
   ORD_SOUMET_TMPFS: "1G"

.env:
   build:
      - echo "No specific environment"

include:
   - project: 'RPN-SI/ci-admin'
     ref: dev
     file: '/ci/.gitlab-ci-config.yml'

#deploy:staging:
#   stage: deploy
#   only:
#      - master
#      - tags
#      - dev
#      - schedules
#   script:
#      - ~/ci-admin-bundle/bin/ci-stage-ssm.sh libs ${CI_PROJECT_NAME} "${CI_COMMIT_TAG}" "${ECCI_PROCESS}"
